---
apiVersion: v1
kind: Secret
metadata:
  name: {namespace}-secret-key
  namespace: {namespace}
stringData:
  secret_key: SomethingVerySecret
type: Opaque
---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: {namespace}
  namespace: {namespace}
spec:
  replicas: {replicacount}
  service_type: nodeport
  postgres_configuration_secret: {namespace}-postgres-configuration
  hostname: {dnsname}.{dnszone}
  secret_key_secret: {namespace}-secret-key
