---
apiVersion: v1
kind: Secret
metadata:
    name: "[servicename]-postgres-configuration"
    namespace: "[servicename]"
stringData:
    host: "[pgserver].postgres.database.azure.com"
    port: "5432"
    database: "[servicename]"
    username: "[servicename]"
    password: "[pguserpwd]"
    sslmode: prefer
    type: unmanaged
type: Opaque
