---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {namespace}-ingress
  namespace: {namespace}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: {dnszone}-clusterissuer
    cert-manager.io/acme-challenge-type: dns01
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {dnsname}.{dnszone}
    secretName: {namespace}-certificate
  rules:
  - host: {dnsname}.{dnszone}
    http:
      paths:
        - pathType: ImplementationSpecific
          path: "/"
          backend:
            service:
              name: {namespace}-service
              port:
                number: 80
