---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "github.com/ansible/awx-operator/config/default?ref=[awxoperator]"
images:
  - name: quay.io/ansible/awx-operator
    newTag: "[awxoperator]"
namespace: "[servicename]"
