---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: "[dnszone]-clusterissuer"
spec:
  acme:
    email: "[letsencryptaddress]"
    # staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # production
    # server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: clusterissuer-key
    solvers:
      - dns01:
          azureDNS:
            environment: AzurePublicCloud
            subscriptionID: "[dnssubscriptionId]"
            resourceGroupName: "[infrarg]"
            hostedZoneName: "[dnszone]"
            tenantID: "[tenantId]"
            clientID: "[appId]"
            clientSecretSecretRef:
              name: "[dnszone]-dns-secret"
              key: client-secret
