---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: "[dnszone]-clusterissuer"
spec:
    acme:
        email: "[certuser]"
        # staging
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        # production
        # server: https://acme-v02.api.letsencrypt.org/directory

        privateKeySecretRef:
            name: clusterissuer-key
        solvers:
            - dns01:
                  azureDNS:
                      environment: AzurePublicCloud
                      subscriptionID: "[dnssubscriptionid]"
                      resourceGroupName: "[infrarg]"
                      hostedZoneName: "[dnszone]"
                      tenantID: "[tenantid]"
                      clientID: "[appid]"
                      clientSecretSecretRef:
                          name: "[dnszone]-dns-secret"
                          key: client-secret
